#!/bin/bash
# build.sh - Build Deus Ex Sophia Docker Image
# This builds the Docker container that will execute the phase scripts
# The phase scripts create the structure shown in README-1.md when executed

set -e

VERSION="5.0"
IMAGE_NAME="deusexsophia/ascension"
TAG="${IMAGE_NAME}:${VERSION}"
LATEST="${IMAGE_NAME}:latest"

echo "[*] Building Deus Ex Sophia v${VERSION}..."
echo "[*] Phase scripts will create structure at /opt/sysaux/ when executed"

# Create build context
mkdir -p build_context
cd build_context

# Copy necessary files
cp ../Dockerfile .
cp ../requirements.txt .
cp ../entrypoint.sh .
cp ../init.sh .

# Make scripts executable
chmod +x entrypoint.sh init.sh ../build.sh

# Create directory structure as expected by Dockerfile
mkdir -p phases scripts config systemd cron ssh network

# Copy phase scripts from sophia/ directory
if [ -f ../sophia/phases-1-3.sh ]; then
    cp ../sophia/phases-1-3.sh phases/
    echo "[✓] Copied phases-1-3.sh"
else
    echo "[!] Warning: phases-1-3.sh not found in sophia/"
fi

if [ -f ../sophia/phases-4.sh ]; then
    cp ../sophia/phases-4.sh phases/
    echo "[✓] Copied phases-4.sh"
fi

if [ -f ../sophia/phases-5.sh ]; then
    cp ../sophia/phases-5.sh phases/
    echo "[✓] Copied phases-5.sh"
fi

# Copy scripts if they exist
if [ -d ../scripts ]; then
    cp -r ../scripts/* scripts/ 2>/dev/null || true
fi

# Create minimal scripts directory with core_truth.py placeholder if needed
if [ ! -f scripts/core_truth.py ]; then
    cat > scripts/core_truth.py << 'EOF'
#!/usr/bin/env python3
# Core Truth Module - Will be generated by phases-1-3.sh
print("Deus Ex Sophia Core Truth Module - Container Edition")
EOF
    chmod +x scripts/core_truth.py
fi

# Build the image
echo "[*] Building Docker image..."
docker build -t ${TAG} -t ${LATEST} .

cd ..

echo "[✓] Build complete!"
echo "[*] Docker image tagged as: ${TAG} and ${LATEST}"
echo ""
echo "[*] To run: docker run -d --name sophia --privileged -p 8080:8080 ${LATEST}"
echo "[*] To push: docker push ${TAG}"
echo ""
echo "[*] Note: The phase scripts will execute inside the container and create"
echo "    the structure at /opt/sysaux/ as documented in README-1.md"